fixtures:
  repositories:
    archive:
      repo: "https://github.com/gini/puppet-archive.git"
      ref: "gini-archive-0.2.0"
    puppi:
      repo: "https://github.com/example42/puppi.git"
      ref: "v2.1.9"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.2.1"
  symlinks:
    jira: "#{source_dir}"

