name 'tohuwabohu-jira'
version '1.0.0'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
source 'https://github.com/tohuwabohu/tohuwabohu-jira.git'
project_page 'https://github.com/tohuwabohu/tohuwabohu-jira'
summary 'Puppet module for Atlassian JIRA'
description 'This module installs and manages Atlassian JIRA.'

dependency 'example42/puppi', '2.x'
dependency 'gini/archive', '0.2.x'
dependency 'puppetlabs/stdlib', '4.x'
